### ISSUE TITLE
Calculation for Width is Incorrect

### ISSUE THREAD

**Issue by rbyrnes** [thepirat000/Snipping-Ocr#2]
https://github.com/thepirat000/Snipping-Ocr/blob/fd18a219caaeb0eff01650339fd8b85b40c9a46b/Snipping%20OCR/SnippingTool/ScreenHelper.cs#L62

Width calculation here will always return 0.

The line's content should be: 
MonitorArea = new Rectangle(mi.Monitor.left, mi.Monitor.top, mi.Monitor.right-**mi.Monitor.left**, mi.Monitor.bottom-mi.Monitor.top),

**Comment by thepirat000** [comment]
thanks! fixed now
